<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class ImportGames extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:import-games';

    protected $description = 'Import games from games_data.json generated by the scraper';

    public function handle()
    {
        $scraperDir = base_path('../scraper');
        $jsonPath = $scraperDir . '/games_data.json';
        
        $this->info('Starting scraper...');

        // Execute Python scraper
        // We assume 'python' is in the PATH. The user should have the venv activated or dependencies installed globally.
        // For better compatibility on Windows, we'll try 'python' then 'py'
        $pythonBinary = 'python';
        
        $process = new \Symfony\Component\Process\Process([$pythonBinary, 'main.py'], $scraperDir);
        $process->setTimeout(300); // 5 minutes timeout
        
        $process->run(function ($type, $buffer) {
            $this->output->write($buffer);
        });

        if (!$process->isSuccessful()) {
            $this->error('The scraper failed to execute.');
            return 1;
        }

        $this->info('Scraper finished. Importing data...');

        if (!file_exists($jsonPath)) {
            $this->error("File not found: {$jsonPath}");
            return 1;
        }

        $data = json_decode(file_get_contents($jsonPath), true);

        if (!$data) {
            $this->error("Invalid JSON data in: {$jsonPath}");
            return 1;
        }

        foreach ($data as $item) {
            $game = \App\Models\Game::updateOrCreate(
                ['name' => $item['name']],
                ['cover_image' => $item['cover_image'] ?? null]
            );

            $store = \App\Models\Store::firstOrCreate(
                ['name' => $item['store']]
            );

            \App\Models\GamePrice::updateOrCreate(
                [
                    'game_id' => $game->id,
                    'store_id' => $store->id,
                ],
                [
                    'price' => $item['price'] ?? 0,
                    'url_link' => $item['url_link'] ?? '',
                ]
            );

            $this->info("Imported/Updated: {$game->name} from {$store->name}");
        }

        $this->info('Import completed successfully.');
        return 0;
    }
}
