<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class ImportGames extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:import-games';

    protected $description = 'Import games from games_data.json generated by the scraper';

    public function handle()
    {
        $jsonPath = base_path('../scraper/games_data.json');

        if (!file_exists($jsonPath)) {
            $this->error("File not found: {$jsonPath}");
            return 1;
        }

        $data = json_decode(file_get_contents($jsonPath), true);

        if (!$data) {
            $this->error("Invalid JSON data in: {$jsonPath}");
            return 1;
        }

        foreach ($data as $item) {
            $game = \App\Models\Game::updateOrCreate(
                ['name' => $item['name']],
                ['cover_image' => $item['cover_image'] ?? null]
            );

            $store = \App\Models\Store::firstOrCreate(
                ['name' => $item['store']]
            );

            \App\Models\GamePrice::updateOrCreate(
                [
                    'game_id' => $game->id,
                    'store_id' => $store->id,
                ],
                [
                    'price' => $item['price'] ?? 0,
                    'url_link' => $item['url_link'] ?? '',
                ]
            );

            $this->info("Imported/Updated: {$game->name} from {$store->name}");
        }

        $this->info('Import completed successfully.');
        return 0;
    }
}
