<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class ImportGames extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:import-games {--fresh : Truncate games and prices before importing} {--skip-scraper : Skip running the Python scraper}';

    protected $description = 'Import games from games_data.json generated by the scraper';

    public function handle()
    {
        $scraperDir = base_path('../scraper');
        $jsonPath = $scraperDir . '/games_data.json';
        
        if (!$this->option('skip-scraper')) {
            $this->info('Starting scraper...');

            // Ejecutar el scraper de Python
            $pythonBinary = 'python';
            
            $process = new \Symfony\Component\Process\Process([$pythonBinary, 'main.py'], $scraperDir);
            $process->setTimeout(300); // Tiempo máximo: 5 minutos
            
            $process->run(function ($type, $buffer) {
                $this->output->write($buffer);
            });

            if (!$process->isSuccessful()) {
                $this->error('The scraper failed to execute.');
                return 1;
            }
        } else {
            $this->info('Skipping scraper, importing from existing JSON...');
        }

        $absoluteJsonPath = realpath($jsonPath) ?: $jsonPath;
        $this->info("Looking for data at: {$absoluteJsonPath}");

        if (!file_exists($jsonPath)) {
            $this->error("File not found: {$jsonPath}");
            return 1;
        }

        if ($this->option('fresh')) {
            $this->warn('Vaciando juegos y precios existentes...');
            \Illuminate\Support\Facades\Schema::disableForeignKeyConstraints();
            \App\Models\GamePrice::truncate();
            \App\Models\Game::truncate();
            // Opcional: También vaciar géneros si se deben actualizar
            // \App\Models\Genre::truncate();
            \Illuminate\Support\Facades\Schema::enableForeignKeyConstraints();
        }

        $data = json_decode(file_get_contents($jsonPath), true);

        if (!$data) {
            $this->error("Invalid JSON data in: {$jsonPath}");
            return 1;
        }

        foreach ($data as $item) {
            $game = \App\Models\Game::updateOrCreate(
                ['name' => $item['name']],
                [
                    'cover_image' => $item['cover_image'] ?? null,
                    'description' => $item['description'] ?? null,
                ]
            );

            // Gestionar géneros
            if (!empty($item['category'])) {
                // Algunas categorías pueden ser cadenas separadas por comas
                $categories = array_map('trim', explode(',', $item['category']));
                $genreIds = [];
                foreach ($categories as $catName) {
                    if ($catName === 'N/A') continue;
                    $genre = \App\Models\Genre::firstOrCreate(['name' => $catName]);
                    $genreIds[] = $genre->id;
                }
                $game->genres()->sync($genreIds);
            }

            $store = \App\Models\Store::firstOrCreate(
                ['name' => $item['store']]
            );

            \App\Models\GamePrice::updateOrCreate(
                [
                    'game_id' => $game->id,
                    'store_id' => $store->id,
                ],
                [
                    'price' => $item['price'] ?? 0,
                    'url_link' => $item['url_link'] ?? '',
                ]
            );

            $this->info("Imported/Updated: {$game->name} from {$store->name}");
        }

        $this->info('Import completed successfully.');
        return 0;
    }
}
